package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/21/11:21:55
 * @comment 根据活动主题获取当前生效的红包信息.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class ActivityRedEnvelopeRspModel
{
	//活动编号 
	@JDataRuleRequired
	private String activityId;

	//活动名称 
	@JDataRuleRequired
	private String activityName;

	//活动类型 
	@JDataRuleRequired
	private String activityType;

	//活动主题 
	private String activitySubject;

	//活动开始时间 
	private String activityStartTime;

	//活动结束时间 
	private String activityEndTime;

	//剩余参加活动次数 
	private String aviliableTimes;

	//当前可领取的优惠券ID 
	private String couponId;

	//优惠券名称 
	private String couponName;

	//奖项等级 
	private String priority;

	//领取开始时间YYYYMMDDHHmmSS 
	private String issueStartTime;

	//领取结束时间YYYYMMDDHHmmSS 
	private String issueEndTime;


	public String getActivityId( ) {
		return activityId;
	}

	public void setActivityId(String arg0 ) {
		activityId = arg0;
	}

	public String getActivityName( ) {
		return activityName;
	}

	public void setActivityName(String arg0 ) {
		activityName = arg0;
	}

	public String getActivityType( ) {
		return activityType;
	}

	public void setActivityType(String arg0 ) {
		activityType = arg0;
	}

	public String getActivitySubject( ) {
		return activitySubject;
	}

	public void setActivitySubject(String arg0 ) {
		activitySubject = arg0;
	}

	public String getActivityStartTime( ) {
		return activityStartTime;
	}

	public void setActivityStartTime(String arg0 ) {
		activityStartTime = arg0;
	}

	public String getActivityEndTime( ) {
		return activityEndTime;
	}

	public void setActivityEndTime(String arg0 ) {
		activityEndTime = arg0;
	}

	public String getAviliableTimes( ) {
		return aviliableTimes;
	}

	public void setAviliableTimes(String arg0 ) {
		aviliableTimes = arg0;
	}

	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getCouponName( ) {
		return couponName;
	}

	public void setCouponName(String arg0 ) {
		couponName = arg0;
	}

	public String getPriority( ) {
		return priority;
	}

	public void setPriority(String arg0 ) {
		priority = arg0;
	}

	public String getIssueStartTime( ) {
		return issueStartTime;
	}

	public void setIssueStartTime(String arg0 ) {
		issueStartTime = arg0;
	}

	public String getIssueEndTime( ) {
		return issueEndTime;
	}

	public void setIssueEndTime(String arg0 ) {
		issueEndTime = arg0;
	}


}

/******** SET values to bean.

++++++++++++

//******* GET valus from bean.

	public static __RET_CLASS__ saveActivityRedEnvelopeResponse( ActivityRedEnvelopeRspModel rspModel )
	{
		__RET_CLASS__ __resultModel = new __RET_CLASS__( );
		__resultModel.setActivityId( rspModel.getActivityId());			//活动编号 
		__resultModel.setActivityName( rspModel.getActivityName());			//活动名称 
		__resultModel.setActivityType( rspModel.getActivityType());			//活动类型 
		__resultModel.setActivitySubject( rspModel.getActivitySubject());			//活动主题 
		__resultModel.setActivityStartTime( rspModel.getActivityStartTime());			//活动开始时间 
		__resultModel.setActivityEndTime( rspModel.getActivityEndTime());			//活动结束时间 
		__resultModel.setAviliableTimes( rspModel.getAviliableTimes());			//剩余参加活动次数 
		__resultModel.setCouponId( rspModel.getCouponId());			//当前可领取的优惠券ID 
		__resultModel.setCouponName( rspModel.getCouponName());			//优惠券名称 
		__resultModel.setPriority( rspModel.getPriority());			//奖项等级 
		__resultModel.setIssueStartTime( rspModel.getIssueStartTime());			//领取开始时间YYYYMMDDHHmmSS 
		__resultModel.setIssueEndTime( rspModel.getIssueEndTime());			//领取结束时间YYYYMMDDHHmmSS 

		return __resultModel;
	}


********/