package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/17/10:12:43
 * @comment 红包校验.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class CheckRedEnvelopeReqModel
{
	//优惠券编号 
	private String couponId;

	//口令 
	private String couponPwd;


	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getCouponPwd( ) {
		return couponPwd;
	}

	public void setCouponPwd(String arg0 ) {
		couponPwd = arg0;
	}


}

/******** SET values to bean.

		CheckRedEnvelopeReqModel reqModel = new CheckRedEnvelopeReqModel( );
		reqModel.setCouponId( null );			//优惠券编号 
		reqModel.setCouponPwd( null );			//口令 


//******* GET valus from bean.

++

********/