package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/25/11:39:46
 * @comment 红包详情.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class DetailRedEnvelopeReqModel
{
	//优惠券编号 
	@JDataRuleRequired
	private String couponId;

	//商户编号 
	@JDataRuleRequired
	private String eCustId;

	//优惠券类型（发券方） 0-银行券；1-商户券；2-个人券
	@JDataRuleRequired
	private String couponType;

	//类别 0-发出的红包；1-收到的红包
	@JDataRuleRequired
	private String queryType;

	//查询记录开始数 
	@JDataRuleRequired
	private String startIndex;

	//条数 
	@JDataRuleRequired
	private String pageSize;


	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getECustId( ) {
		return eCustId;
	}

	public void setECustId(String arg0 ) {
		eCustId = arg0;
	}

	public String getCouponType( ) {
		return couponType;
	}

	public void setCouponType(String arg0 ) {
		couponType = arg0;
	}

	public String getQueryType( ) {
		return queryType;
	}

	public void setQueryType(String arg0 ) {
		queryType = arg0;
	}

	public String getStartIndex( ) {
		return startIndex;
	}

	public void setStartIndex(String arg0 ) {
		startIndex = arg0;
	}

	public String getPageSize( ) {
		return pageSize;
	}

	public void setPageSize(String arg0 ) {
		pageSize = arg0;
	}


}

/******** SET values to bean.

		DetailRedEnvelopeReqModel reqModel = new DetailRedEnvelopeReqModel( );
		reqModel.setCouponId( null );			//优惠券编号 
		reqModel.setECustId( null );			//商户编号 
		reqModel.setCouponType( null );			//优惠券类型（发券方） 0-银行券；1-商户券；2-个人券
		reqModel.setQueryType( null );			//类别 0-发出的红包；1-收到的红包
		reqModel.setStartIndex( null );			//查询记录开始数 
		reqModel.setPageSize( null );			//条数 


//******* GET valus from bean.

++++++

********/