package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/25/11:39:46
 * @comment 红包详情.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class DetailRedEnvelopeRspListModel
{
	//商户编号 
	private String eCustId;

	//商户名称 
	private String eCustName;

	//客户编号 
	private String custId;

	//客户名称 
	private String custName;

	//优惠券唯一编号 
	private String couponUUID;

	//优惠券编号 
	private String couponId;

	//优惠券名 
	private String couponName;

	//优惠券生效时间 
	private String validityStartTime;

	//优惠券失效时间 
	private String validityEndTime;

	//优惠券参数 
	private String typeParameter;

	//优惠券状态 
	private String state;

	//优惠券图片 
	private String photo;

	//优惠券描述 
	private String couponDesc;

	//优惠券类型 
	private String couponTemplateId;

	//优惠金额 
	private String discountAmount;

	//是否手气最佳 1-是，只有红包和现金券时返回
	private String couponMaxAmount;

	//发放类型 3-手动领取;4-自动领取;5-口令。
	private String issueType;

	//优惠券类型（发券方） 0-银行券；1-商户券；2-个人券
	private String couponType;

	//口令 
	private String couponPwd;

	//领取时间 
	private String obtainDate;

	//客户手机号 
	private String mobile;


	public String getECustId( ) {
		return eCustId;
	}

	public void setECustId(String arg0 ) {
		eCustId = arg0;
	}

	public String getECustName( ) {
		return eCustName;
	}

	public void setECustName(String arg0 ) {
		eCustName = arg0;
	}

	public String getCustId( ) {
		return custId;
	}

	public void setCustId(String arg0 ) {
		custId = arg0;
	}

	public String getCustName( ) {
		return custName;
	}

	public void setCustName(String arg0 ) {
		custName = arg0;
	}

	public String getCouponUUID( ) {
		return couponUUID;
	}

	public void setCouponUUID(String arg0 ) {
		couponUUID = arg0;
	}

	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getCouponName( ) {
		return couponName;
	}

	public void setCouponName(String arg0 ) {
		couponName = arg0;
	}

	public String getValidityStartTime( ) {
		return validityStartTime;
	}

	public void setValidityStartTime(String arg0 ) {
		validityStartTime = arg0;
	}

	public String getValidityEndTime( ) {
		return validityEndTime;
	}

	public void setValidityEndTime(String arg0 ) {
		validityEndTime = arg0;
	}

	public String getTypeParameter( ) {
		return typeParameter;
	}

	public void setTypeParameter(String arg0 ) {
		typeParameter = arg0;
	}

	public String getState( ) {
		return state;
	}

	public void setState(String arg0 ) {
		state = arg0;
	}

	public String getPhoto( ) {
		return photo;
	}

	public void setPhoto(String arg0 ) {
		photo = arg0;
	}

	public String getCouponDesc( ) {
		return couponDesc;
	}

	public void setCouponDesc(String arg0 ) {
		couponDesc = arg0;
	}

	public String getCouponTemplateId( ) {
		return couponTemplateId;
	}

	public void setCouponTemplateId(String arg0 ) {
		couponTemplateId = arg0;
	}

	public String getDiscountAmount( ) {
		return discountAmount;
	}

	public void setDiscountAmount(String arg0 ) {
		discountAmount = arg0;
	}

	public String getCouponMaxAmount( ) {
		return couponMaxAmount;
	}

	public void setCouponMaxAmount(String arg0 ) {
		couponMaxAmount = arg0;
	}

	public String getIssueType( ) {
		return issueType;
	}

	public void setIssueType(String arg0 ) {
		issueType = arg0;
	}

	public String getCouponType( ) {
		return couponType;
	}

	public void setCouponType(String arg0 ) {
		couponType = arg0;
	}

	public String getCouponPwd( ) {
		return couponPwd;
	}

	public void setCouponPwd(String arg0 ) {
		couponPwd = arg0;
	}

	public String getObtainDate( ) {
		return obtainDate;
	}

	public void setObtainDate(String arg0 ) {
		obtainDate = arg0;
	}

	public String getMobile( ) {
		return mobile;
	}

	public void setMobile(String arg0 ) {
		mobile = arg0;
	}


}

/******** SET values to bean.

+++++++++++++++++++++

//******* GET valus from bean.

		List<DetailRedEnvelopeRspListModel> __resultList1 = new ArrayList<DetailRedEnvelopeRspListModel>();
		for ( int i = 0; i < rspModel.getList().size(); ++i )
		{
			__RSP_ITEM_CLASS__ rspItem = rspModel.getList().get(i);

			__RET_CLASS__ __resultItem = new __RET_CLASS__( );
			__resultItem.setECustId( rspItem.getECustId());			//商户编号 
			__resultItem.setECustName( rspItem.getECustName());			//商户名称 
			__resultItem.setCustId( rspItem.getCustId());			//客户编号 
			__resultItem.setCustName( rspItem.getCustName());			//客户名称 
			__resultItem.setCouponUUID( rspItem.getCouponUUID());			//优惠券唯一编号 
			__resultItem.setCouponId( rspItem.getCouponId());			//优惠券编号 
			__resultItem.setCouponName( rspItem.getCouponName());			//优惠券名 
			__resultItem.setValidityStartTime( rspItem.getValidityStartTime());			//优惠券生效时间 
			__resultItem.setValidityEndTime( rspItem.getValidityEndTime());			//优惠券失效时间 
			__resultItem.setTypeParameter( rspItem.getTypeParameter());			//优惠券参数 
			__resultItem.setState( rspItem.getState());			//优惠券状态 
			__resultItem.setPhoto( rspItem.getPhoto());			//优惠券图片 
			__resultItem.setCouponDesc( rspItem.getCouponDesc());			//优惠券描述 
			__resultItem.setCouponTemplateId( rspItem.getCouponTemplateId());			//优惠券类型 
			__resultItem.setDiscountAmount( rspItem.getDiscountAmount());			//优惠金额 
			__resultItem.setCouponMaxAmount( rspItem.getCouponMaxAmount());			//是否手气最佳 1-是，只有红包和现金券时返回
			__resultItem.setIssueType( rspItem.getIssueType());			//发放类型 3-手动领取;4-自动领取;5-口令。
			__resultItem.setCouponType( rspItem.getCouponType());			//优惠券类型（发券方） 0-银行券；1-商户券；2-个人券
			__resultItem.setCouponPwd( rspItem.getCouponPwd());			//口令 
			__resultItem.setObtainDate( rspItem.getObtainDate());			//领取时间 
			__resultItem.setMobile( rspItem.getMobile());			//客户手机号 

			__resultList1.add(__resultItem);
		}


********/