package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/25/11:39:46
 * @comment 红包详情.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class DetailRedEnvelopeRspModel
{
	//商户编号 
	@JDataRuleRequired
	private String eCustId;

	//商户名称 
	@JDataRuleRequired
	private String eCustName;

	//优惠券编号 
	@JDataRuleRequired
	private String couponId;

	//优惠券名 
	@JDataRuleRequired
	private String couponName;

	//优惠券数量限额 
	@JDataRuleRequired
	private String couponQuota;

	//优惠券模板编号 21-固定金额红包；22-随机金额红包
	@JDataRuleRequired
	private String couponTemplateId;

	//优惠券参数 
	@JDataRuleRequired
	private String couponTypeParameter;

	//发放张数 
	@JDataRuleRequired
	private String count;

	//发放金额 
	@JDataRuleRequired
	private String amount;

	//被领取金额 
	@JDataRuleRequired
	private String usedAmount;

	//已使用张数 
	@JDataRuleRequired
	private String usedCount;

	//优惠券类型（发券方）0-银行券；1-商户券；2-个人券 
	@JDataRuleRequired
	private String couponType;

	//是否实名制 默认为0关闭实名制 0-关闭实名制度；1-开启实名制
	private String realNameFlag;

	//发放类型 3-手动领取;4-自动领取;5-口令。
	@JDataRuleRequired
	private String issueType;

	//口令 
	@JDataRuleRequired
	private String couponPwd;

	//客户收到的金额（只限查询类型为收到时返回） 
	@JDataRuleRequired
	private String discountAmount;

	//有效红包是否超过有效时间标志 1-过期
	private String isOverDue;

	//是否有下一页 true:有；false:无
	@JDataRuleRequired
	private String isNext;

	//null null
	private List<DetailRedEnvelopeRspListModel> list;


	public String getECustId( ) {
		return eCustId;
	}

	public void setECustId(String arg0 ) {
		eCustId = arg0;
	}

	public String getECustName( ) {
		return eCustName;
	}

	public void setECustName(String arg0 ) {
		eCustName = arg0;
	}

	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getCouponName( ) {
		return couponName;
	}

	public void setCouponName(String arg0 ) {
		couponName = arg0;
	}

	public String getCouponQuota( ) {
		return couponQuota;
	}

	public void setCouponQuota(String arg0 ) {
		couponQuota = arg0;
	}

	public String getCouponTemplateId( ) {
		return couponTemplateId;
	}

	public void setCouponTemplateId(String arg0 ) {
		couponTemplateId = arg0;
	}

	public String getCouponTypeParameter( ) {
		return couponTypeParameter;
	}

	public void setCouponTypeParameter(String arg0 ) {
		couponTypeParameter = arg0;
	}

	public String getCount( ) {
		return count;
	}

	public void setCount(String arg0 ) {
		count = arg0;
	}

	public String getAmount( ) {
		return amount;
	}

	public void setAmount(String arg0 ) {
		amount = arg0;
	}

	public String getUsedAmount( ) {
		return usedAmount;
	}

	public void setUsedAmount(String arg0 ) {
		usedAmount = arg0;
	}

	public String getUsedCount( ) {
		return usedCount;
	}

	public void setUsedCount(String arg0 ) {
		usedCount = arg0;
	}

	public String getCouponType( ) {
		return couponType;
	}

	public void setCouponType(String arg0 ) {
		couponType = arg0;
	}

	public String getRealNameFlag( ) {
		return realNameFlag;
	}

	public void setRealNameFlag(String arg0 ) {
		realNameFlag = arg0;
	}

	public String getIssueType( ) {
		return issueType;
	}

	public void setIssueType(String arg0 ) {
		issueType = arg0;
	}

	public String getCouponPwd( ) {
		return couponPwd;
	}

	public void setCouponPwd(String arg0 ) {
		couponPwd = arg0;
	}

	public String getDiscountAmount( ) {
		return discountAmount;
	}

	public void setDiscountAmount(String arg0 ) {
		discountAmount = arg0;
	}

	public String getIsOverDue( ) {
		return isOverDue;
	}

	public void setIsOverDue(String arg0 ) {
		isOverDue = arg0;
	}

	public String getIsNext( ) {
		return isNext;
	}

	public void setIsNext(String arg0 ) {
		isNext = arg0;
	}

	public List<DetailRedEnvelopeRspListModel> getList( ) {
		return list;
	}

	public void setList(List<DetailRedEnvelopeRspListModel> arg0 ) {
		list = arg0;
	}


}

/******** SET values to bean.

+++++++++++++++++++

//******* GET valus from bean.

	public static __RET_CLASS__ saveDetailRedEnvelopeResponse( DetailRedEnvelopeRspModel rspModel )
	{
		__RET_CLASS__ __resultModel = new __RET_CLASS__( );
		__resultModel.setECustId( rspModel.getECustId());			//商户编号 
		__resultModel.setECustName( rspModel.getECustName());			//商户名称 
		__resultModel.setCouponId( rspModel.getCouponId());			//优惠券编号 
		__resultModel.setCouponName( rspModel.getCouponName());			//优惠券名 
		__resultModel.setCouponQuota( rspModel.getCouponQuota());			//优惠券数量限额 
		__resultModel.setCouponTemplateId( rspModel.getCouponTemplateId());			//优惠券模板编号 21-固定金额红包；22-随机金额红包
		__resultModel.setCouponTypeParameter( rspModel.getCouponTypeParameter());			//优惠券参数 
		__resultModel.setCount( rspModel.getCount());			//发放张数 
		__resultModel.setAmount( rspModel.getAmount());			//发放金额 
		__resultModel.setUsedAmount( rspModel.getUsedAmount());			//被领取金额 
		__resultModel.setUsedCount( rspModel.getUsedCount());			//已使用张数 
		__resultModel.setCouponType( rspModel.getCouponType());			//优惠券类型（发券方）0-银行券；1-商户券；2-个人券 
		__resultModel.setRealNameFlag( rspModel.getRealNameFlag());			//是否实名制 默认为0关闭实名制 0-关闭实名制度；1-开启实名制
		__resultModel.setIssueType( rspModel.getIssueType());			//发放类型 3-手动领取;4-自动领取;5-口令。
		__resultModel.setCouponPwd( rspModel.getCouponPwd());			//口令 
		__resultModel.setDiscountAmount( rspModel.getDiscountAmount());			//客户收到的金额（只限查询类型为收到时返回） 
		__resultModel.setIsOverDue( rspModel.getIsOverDue());			//有效红包是否超过有效时间标志 1-过期
		__resultModel.setIsNext( rspModel.getIsNext());			//是否有下一页 true:有；false:无
		__resultModel.setList( rspModel.getList());			//null null

		return __resultModel;
	}


********/