package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行情红包.
 * @author autocode generated by bxz
 * @date 2017/04/20/17:06:23
 * @comment 发放红包.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class HandOutRedEnvelopeReqModel
{
	//优惠券模版编号 21-固定金额红包;22-随机金额红包
	@JDataRuleRequired
	private String couponTemplateId;

	//金额 
	@JDataRuleRequired
	private String amount;

	//红包个数. 
	@JDataRuleRequired
	private String count;

	//发放类型 3-手动领取;4-自动领取;5-口令
	@JDataRuleRequired
	private String issueType;

	//卡号 
	@JDataRuleRequired
	private String accountNo;

	//户名 
	@JDataRuleRequired
	private String accountName;

	//密码 
	@JDataRuleRequired
	private String accountPwd;

	//是否匿名发送 0-匿名，1-实名
	@JDataRuleRequired
	private String realNameFlag;

	//设备UUID 
	private String uuid;


	public String getCouponTemplateId( ) {
		return couponTemplateId;
	}

	public void setCouponTemplateId(String arg0 ) {
		couponTemplateId = arg0;
	}

	public String getAmount( ) {
		return amount;
	}

	public void setAmount(String arg0 ) {
		amount = arg0;
	}

	public String getCount( ) {
		return count;
	}

	public void setCount(String arg0 ) {
		count = arg0;
	}

	public String getIssueType( ) {
		return issueType;
	}

	public void setIssueType(String arg0 ) {
		issueType = arg0;
	}

	public String getAccountNo( ) {
		return accountNo;
	}

	public void setAccountNo(String arg0 ) {
		accountNo = arg0;
	}

	public String getAccountName( ) {
		return accountName;
	}

	public void setAccountName(String arg0 ) {
		accountName = arg0;
	}

	public String getAccountPwd( ) {
		return accountPwd;
	}

	public void setAccountPwd(String arg0 ) {
		accountPwd = arg0;
	}

	public String getRealNameFlag( ) {
		return realNameFlag;
	}

	public void setRealNameFlag(String arg0 ) {
		realNameFlag = arg0;
	}

	public String getUuid( ) {
		return uuid;
	}

	public void setUuid(String arg0 ) {
		uuid = arg0;
	}


}

/******** SET values to bean.

		HandOutRedEnvelopeReqModel reqModel = new HandOutRedEnvelopeReqModel( );
		reqModel.setCouponTemplateId( null );			//优惠券模版编号 21-固定金额红包;22-随机金额红包
		reqModel.setAmount( null );			//金额 
		reqModel.setCount( null );			//红包个数. 
		reqModel.setIssueType( null );			//发放类型 3-手动领取;4-自动领取;5-口令
		reqModel.setAccountNo( null );			//卡号 
		reqModel.setAccountName( null );			//户名 
		reqModel.setAccountPwd( null );			//密码 
		reqModel.setRealNameFlag( null );			//是否匿名发送 0-匿名，1-实名
		reqModel.setUuid( null );			//设备UUID 


//******* GET valus from bean.

+++++++++

********/