package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行情红包.
 * @author autocode generated by bxz
 * @date 2017/04/20/17:06:23
 * @comment 发放红包.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class HandOutRedEnvelopeRspModel
{
	//优惠券编号 
	private String couponId;

	//口令 
	private String couponPwd;

	//发放类型 
	private String issueType;

	//优惠券类型（发券方） 
	private String couponType;

	//优惠券状态. 
	private String couponStatus;


	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getCouponPwd( ) {
		return couponPwd;
	}

	public void setCouponPwd(String arg0 ) {
		couponPwd = arg0;
	}

	public String getIssueType( ) {
		return issueType;
	}

	public void setIssueType(String arg0 ) {
		issueType = arg0;
	}

	public String getCouponType( ) {
		return couponType;
	}

	public void setCouponType(String arg0 ) {
		couponType = arg0;
	}

	public String getCouponStatus( ) {
		return couponStatus;
	}

	public void setCouponStatus(String arg0 ) {
		couponStatus = arg0;
	}


}

/******** SET values to bean.

+++++

//******* GET valus from bean.

	public static __RET_CLASS__ saveHandOutRedEnvelopeResponse( HandOutRedEnvelopeRspModel rspModel )
	{
		__RET_CLASS__ __resultModel = new __RET_CLASS__( );
		__resultModel.setCouponId( rspModel.getCouponId());			//优惠券编号 
		__resultModel.setCouponPwd( rspModel.getCouponPwd());			//口令 
		__resultModel.setIssueType( rspModel.getIssueType());			//发放类型 
		__resultModel.setCouponType( rspModel.getCouponType());			//优惠券类型（发券方） 
		__resultModel.setCouponStatus( rspModel.getCouponStatus());			//优惠券状态. 

		return __resultModel;
	}


********/