package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/25/11:39:23
 * @comment 收发红包统计.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class LogsRedEnvelopeReqModel
{
	//类别 0-发出的红包；1-收到的红包
	@JDataRuleRequired
	private String queryType;

	//查询记录开始数 
	@JDataRuleRequired
	private String startIndex;

	//条数 
	@JDataRuleRequired
	private String pageSize;


	public String getQueryType( ) {
		return queryType;
	}

	public void setQueryType(String arg0 ) {
		queryType = arg0;
	}

	public String getStartIndex( ) {
		return startIndex;
	}

	public void setStartIndex(String arg0 ) {
		startIndex = arg0;
	}

	public String getPageSize( ) {
		return pageSize;
	}

	public void setPageSize(String arg0 ) {
		pageSize = arg0;
	}


}

/******** SET values to bean.

		LogsRedEnvelopeReqModel reqModel = new LogsRedEnvelopeReqModel( );
		reqModel.setQueryType( null );			//类别 0-发出的红包；1-收到的红包
		reqModel.setStartIndex( null );			//查询记录开始数 
		reqModel.setPageSize( null );			//条数 


//******* GET valus from bean.

+++

********/