package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/25/11:39:23
 * @comment 收发红包统计.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class LogsRedEnvelopeRspModel
{
	//总记录 
	@JDataRuleRequired
	private String totalLogNum;

	//总金额 
	@JDataRuleRequired
	private String totalAmt;

	//是否有下一页 true:有；false:无
	@JDataRuleRequired
	private String isNext;

	//null null
	private List<LogsRedEnvelopeRspListModel> list;


	public String getTotalLogNum( ) {
		return totalLogNum;
	}

	public void setTotalLogNum(String arg0 ) {
		totalLogNum = arg0;
	}

	public String getTotalAmt( ) {
		return totalAmt;
	}

	public void setTotalAmt(String arg0 ) {
		totalAmt = arg0;
	}

	public String getIsNext( ) {
		return isNext;
	}

	public void setIsNext(String arg0 ) {
		isNext = arg0;
	}

	public List<LogsRedEnvelopeRspListModel> getList( ) {
		return list;
	}

	public void setList(List<LogsRedEnvelopeRspListModel> arg0 ) {
		list = arg0;
	}


}

/******** SET values to bean.

++++

//******* GET valus from bean.

	public static __RET_CLASS__ saveLogsRedEnvelopeResponse( LogsRedEnvelopeRspModel rspModel )
	{
		__RET_CLASS__ __resultModel = new __RET_CLASS__( );
		__resultModel.setTotalLogNum( rspModel.getTotalLogNum());			//总记录 
		__resultModel.setTotalAmt( rspModel.getTotalAmt());			//总金额 
		__resultModel.setIsNext( rspModel.getIsNext());			//是否有下一页 true:有；false:无
		__resultModel.setList( rspModel.getList());			//null null

		return __resultModel;
	}


********/