package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/25/11:39:23
 * @comment 收发红包统计.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class LogsRedEnvelopeRspListModel
{
	//商户编号 
	private String eCustId;

	//商户名称 
	private String eCustName;

	//客户编号 
	private String custId;

	//客户名称 
	private String custName;

	//优惠券唯一编号 
	private String couponUUID;

	//优惠券编号 
	private String couponId;

	//优惠券名 
	private String couponName;

	//优惠券生效时间 
	private String validityStartTime;

	//优惠券失效时间 
	private String validityEndTime;

	//优惠券参数 
	private String typeParameter;

	//是否实名制 默认为0关闭实名制 0-关闭实名制度；1-开启实名制
	private String realNameFlag;

	//优惠券发放状态 0-无效，1-有效，2-暂存 ，3-待审核，4-审核不通过，5-待扣款，6-发放失败，7-拆包处理中
	private String couponStatus;

	//优惠券接收状态 0-未使用；1-已使用；2-已失效；3-未领取；4-已转赠待领取；5-已转赠；6-红包发放中；7-红包发放成功；8-红包退款中；9-红包退款失败；10-红包退款成功
	private String state;

	//优惠券图片 
	private String photo;

	//优惠券描述 
	private String couponDesc;

	//优惠券类型 
	private String couponTemplateId;

	//红包发放数量 
	private String count;

	//已使用张数（发红包记录中存在） 
	private String usedCount;

	//优惠金额 
	private String discountAmount;

	//红包退款金额 
	private String refundAmount;

	//发放类型 3-手动领取;4-自动领取;5-口令
	private String issueType;

	//优惠券类型（发券方） 
	private String couponType;

	//口令 
	private String couponPwd;

	//有效红包是否超过有效时间标志 1-过期
	private String isOverDue;

	//领取时间（收取记录里返回） 
	private String obtainDate;

	//客户手机号 
	private String mobile;


	public String getECustId( ) {
		return eCustId;
	}

	public void setECustId(String arg0 ) {
		eCustId = arg0;
	}

	public String getECustName( ) {
		return eCustName;
	}

	public void setECustName(String arg0 ) {
		eCustName = arg0;
	}

	public String getCustId( ) {
		return custId;
	}

	public void setCustId(String arg0 ) {
		custId = arg0;
	}

	public String getCustName( ) {
		return custName;
	}

	public void setCustName(String arg0 ) {
		custName = arg0;
	}

	public String getCouponUUID( ) {
		return couponUUID;
	}

	public void setCouponUUID(String arg0 ) {
		couponUUID = arg0;
	}

	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getCouponName( ) {
		return couponName;
	}

	public void setCouponName(String arg0 ) {
		couponName = arg0;
	}

	public String getValidityStartTime( ) {
		return validityStartTime;
	}

	public void setValidityStartTime(String arg0 ) {
		validityStartTime = arg0;
	}

	public String getValidityEndTime( ) {
		return validityEndTime;
	}

	public void setValidityEndTime(String arg0 ) {
		validityEndTime = arg0;
	}

	public String getTypeParameter( ) {
		return typeParameter;
	}

	public void setTypeParameter(String arg0 ) {
		typeParameter = arg0;
	}

	public String getRealNameFlag( ) {
		return realNameFlag;
	}

	public void setRealNameFlag(String arg0 ) {
		realNameFlag = arg0;
	}

	public String getCouponStatus( ) {
		return couponStatus;
	}

	public void setCouponStatus(String arg0 ) {
		couponStatus = arg0;
	}

	public String getState( ) {
		return state;
	}

	public void setState(String arg0 ) {
		state = arg0;
	}

	public String getPhoto( ) {
		return photo;
	}

	public void setPhoto(String arg0 ) {
		photo = arg0;
	}

	public String getCouponDesc( ) {
		return couponDesc;
	}

	public void setCouponDesc(String arg0 ) {
		couponDesc = arg0;
	}

	public String getCouponTemplateId( ) {
		return couponTemplateId;
	}

	public void setCouponTemplateId(String arg0 ) {
		couponTemplateId = arg0;
	}

	public String getCount( ) {
		return count;
	}

	public void setCount(String arg0 ) {
		count = arg0;
	}

	public String getUsedCount( ) {
		return usedCount;
	}

	public void setUsedCount(String arg0 ) {
		usedCount = arg0;
	}

	public String getDiscountAmount( ) {
		return discountAmount;
	}

	public void setDiscountAmount(String arg0 ) {
		discountAmount = arg0;
	}

	public String getRefundAmount( ) {
		return refundAmount;
	}

	public void setRefundAmount(String arg0 ) {
		refundAmount = arg0;
	}

	public String getIssueType( ) {
		return issueType;
	}

	public void setIssueType(String arg0 ) {
		issueType = arg0;
	}

	public String getCouponType( ) {
		return couponType;
	}

	public void setCouponType(String arg0 ) {
		couponType = arg0;
	}

	public String getCouponPwd( ) {
		return couponPwd;
	}

	public void setCouponPwd(String arg0 ) {
		couponPwd = arg0;
	}

	public String getIsOverDue( ) {
		return isOverDue;
	}

	public void setIsOverDue(String arg0 ) {
		isOverDue = arg0;
	}

	public String getObtainDate( ) {
		return obtainDate;
	}

	public void setObtainDate(String arg0 ) {
		obtainDate = arg0;
	}

	public String getMobile( ) {
		return mobile;
	}

	public void setMobile(String arg0 ) {
		mobile = arg0;
	}


}

/******** SET values to bean.

++++++++++++++++++++++++++

//******* GET valus from bean.

		List<LogsRedEnvelopeRspListModel> __resultList1 = new ArrayList<LogsRedEnvelopeRspListModel>();
		for ( int i = 0; i < rspModel.getList().size(); ++i )
		{
			__RSP_ITEM_CLASS__ rspItem = rspModel.getList().get(i);

			__RET_CLASS__ __resultItem = new __RET_CLASS__( );
			__resultItem.setECustId( rspItem.getECustId());			//商户编号 
			__resultItem.setECustName( rspItem.getECustName());			//商户名称 
			__resultItem.setCustId( rspItem.getCustId());			//客户编号 
			__resultItem.setCustName( rspItem.getCustName());			//客户名称 
			__resultItem.setCouponUUID( rspItem.getCouponUUID());			//优惠券唯一编号 
			__resultItem.setCouponId( rspItem.getCouponId());			//优惠券编号 
			__resultItem.setCouponName( rspItem.getCouponName());			//优惠券名 
			__resultItem.setValidityStartTime( rspItem.getValidityStartTime());			//优惠券生效时间 
			__resultItem.setValidityEndTime( rspItem.getValidityEndTime());			//优惠券失效时间 
			__resultItem.setTypeParameter( rspItem.getTypeParameter());			//优惠券参数 
			__resultItem.setRealNameFlag( rspItem.getRealNameFlag());			//是否实名制 默认为0关闭实名制 0-关闭实名制度；1-开启实名制
			__resultItem.setCouponStatus( rspItem.getCouponStatus());			//优惠券发放状态 0-无效，1-有效，2-暂存 ，3-待审核，4-审核不通过，5-待扣款，6-发放失败，7-拆包处理中
			__resultItem.setState( rspItem.getState());			//优惠券接收状态 0-未使用；1-已使用；2-已失效；3-未领取；4-已转赠待领取；5-已转赠；6-红包发放中；7-红包发放成功；8-红包退款中；9-红包退款失败；10-红包退款成功
			__resultItem.setPhoto( rspItem.getPhoto());			//优惠券图片 
			__resultItem.setCouponDesc( rspItem.getCouponDesc());			//优惠券描述 
			__resultItem.setCouponTemplateId( rspItem.getCouponTemplateId());			//优惠券类型 
			__resultItem.setCount( rspItem.getCount());			//红包发放数量 
			__resultItem.setUsedCount( rspItem.getUsedCount());			//已使用张数（发红包记录中存在） 
			__resultItem.setDiscountAmount( rspItem.getDiscountAmount());			//优惠金额 
			__resultItem.setRefundAmount( rspItem.getRefundAmount());			//红包退款金额 
			__resultItem.setIssueType( rspItem.getIssueType());			//发放类型 3-手动领取;4-自动领取;5-口令
			__resultItem.setCouponType( rspItem.getCouponType());			//优惠券类型（发券方） 
			__resultItem.setCouponPwd( rspItem.getCouponPwd());			//口令 
			__resultItem.setIsOverDue( rspItem.getIsOverDue());			//有效红包是否超过有效时间标志 1-过期
			__resultItem.setObtainDate( rspItem.getObtainDate());			//领取时间（收取记录里返回） 
			__resultItem.setMobile( rspItem.getMobile());			//客户手机号 

			__resultList1.add(__resultItem);
		}


********/