package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/11/12:04:07
 * @comment 拆红包.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class UnpackRedEnvelopeReqModel
{
	//优惠券编号 
	private String couponId;

	//商户编号 
	private String eCustId;


	public String getCouponId( ) {
		return couponId;
	}

	public void setCouponId(String arg0 ) {
		couponId = arg0;
	}

	public String getECustId( ) {
		return eCustId;
	}

	public void setECustId(String arg0 ) {
		eCustId = arg0;
	}


}

/******** SET values to bean.

		UnpackRedEnvelopeReqModel reqModel = new UnpackRedEnvelopeReqModel( );
		reqModel.setCouponId( null );			//优惠券编号 
		reqModel.setECustId( null );			//商户编号 


//******* GET valus from bean.

++

********/