package ebcs.app.auto.transmodel.redEnvelope;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 行庆红包.
 * @author autocode generated by bxz
 * @date 2017/04/11/12:04:07
 * @comment 拆红包.
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class UnpackRedEnvelopeRspModel
{
	//优惠券唯一编号 
	@JDataRuleRequired
	private String couponUUID;

	//优惠金额 
	@JDataRuleRequired
	private String discountAmount;


	public String getCouponUUID( ) {
		return couponUUID;
	}

	public void setCouponUUID(String arg0 ) {
		couponUUID = arg0;
	}

	public String getDiscountAmount( ) {
		return discountAmount;
	}

	public void setDiscountAmount(String arg0 ) {
		discountAmount = arg0;
	}


}

/******** SET values to bean.

++

//******* GET valus from bean.

	public static __RET_CLASS__ saveUnpackRedEnvelopeResponse( UnpackRedEnvelopeRspModel rspModel )
	{
		__RET_CLASS__ __resultModel = new __RET_CLASS__( );
		__resultModel.setCouponUUID( rspModel.getCouponUUID());			//优惠券唯一编号 
		__resultModel.setDiscountAmount( rspModel.getDiscountAmount());			//优惠金额 

		return __resultModel;
	}


********/