package vegos.app.auto.transmodel.chk;

import java.util.List;
import jplat.tools.data.validate.JDataRuleRequired;


/**
 * @system 平台基础能力监测
 * @author autocode generated by zhangcq
 * @date 2018/04/25/20:36:50
 * @comment Trans服务健康监测
 * @charset utf-8
 * @change 建立新接口.
 */
 
public class HealthCheckerRspModel
{
	//返回消息 
	private String rspmsg;


	public String getRspmsg( ) {
		return rspmsg;
	}

	public void setRspmsg(String arg0 ) {
		rspmsg = arg0;
	}


}

/******** SET values to bean.

+

//******* GET valus from bean.

	public static __RET_CLASS__ saveHealthCheckerResponse( HealthCheckerRspModel rspModel )
	{
		__RET_CLASS__ __resultModel = new __RET_CLASS__( );
		__resultModel.setRspmsg( rspModel.getRspmsg());			//返回消息 

		return __resultModel;
	}


********/